services:
  backend:
    build: .
    container_name: gender-api
    ports:
      - "3000:3000"
  backend-two:
    build: .
    container_name: email-api
    ports:
      - "4000:4000"
  backend-three:
    build: .
    container_name: age-api
    ports:
      - "4001:4001"